# angle_finder
realsense_fov: 1.204277184 # radians
realsense_res_x: 640 #pixel width of image frames
min_detection_probability: 0.5
filter_out_farther_props: true

# distance_finder
angle_error_adjustment: 0.01 #radians TUNING

max_lidar_range: 29 #meters - should be slightly less than real range, or accurate range 
min_lidar_range: 0.1 #meters - should be slight larger than real, or accurate range

min_circle_pts: 6 # minimum number of points necessary for radius checking
marker_radius: 0.127 #meters
small_buoy_radius: 0.1015 #meters - TODO: adjust at comp
large_buoy_radius: 0.184 #meters - radius for red buoy in sim, TODO: adjust at comp
marker_radius_range: 0.5 #meters - acceptable range for marker radius (radius +/- range)
small_buoy_radius_range: 0.075 #meters - acceptable range for sm. buoy radius
large_buoy_radius_range: 0.1 #meters - acceptable range for lg. buoy radius
lidar_point_range: 0.3 #meters - how close points should be for radius checking
check_small_buoys: true # boolean - are we checking for small buoys separate from large buoys

valid_prop_labels: ["red_marker", "green_marker", "yellow_buoy", "blue_buoy", "green_buoy", "red_buoy", "buoy", "marker"] # valid labels for props

# prop map
mapping_safety_radius: 3.0

# fake_angle_finder
theta_1: 0.01 #radians
theta_2: 3.14 #radians

# Position of Lidar from boat center 
lidar_position: 0.245 # meters
