# angle_finder
realsense_fov: 1.204277184 # radians
realsense_res_x: 1920 #pixel width of image frames

# distance_finder
angle_error_adjustment: 0.0 #radians TUNING

max_lidar_range: 29 #meters - should be slightly less than real range, or accurate range 
min_lidar_range: 0.1 #meters - should be slight larger than real, or accurate range

min_circle_pts: 6 # minimum number of points necessary for radius checking
marker_radius: 0.127 #meters
large_buoy_radius: 0.184 #meters
small_buoy_radius: 0.1015 #meters
prop_range: 0.05 #meters - acceptable range for prop radius (radius +/- prop_range)
lidar_point_range: 0.3 #meters - how close points should be for radius checking

valid_prop_labels: ["red_marker", "green_marker", "yellow_buoy", "blue_buoy", "green_buoy", "red_buoy"] # valid labels for props

# prop map
mapping_safety_radius: 3.0

# fake_angle_finder
theta_1: 0.01 #radians
theta_2: 3.14 #radians

# Position of Lidar from boat center 
lidar_position: 1.6 # meters

